:github-address: https://github.com/hazelcast-guides/caching-springboot-jcache
:templates-url: templates:ROOT:page$/
:hazelcast: Hazelcast IMDG
:framework: Spring Boot
= Using Spring Boot with JCache and Hazelcast

This guide will get you started to use Hazelcast via JCache provider for your Spring Boot application.

include::{templates-url}/link-to-repo.adoc[]

== What You’ll Learn

In this guide, you'll deploy a Spring Boot application that uses JCache with Hazelcast implementation.

== Prerequisites

- ~5 minutes
- JDK 1.8+
- Apache Maven 3.2+

== Spring Boot Application

To leverage JCache in your Spring Boot application, you will need to:

- add `org.springframework.boot:spring-boot-starter-cache` dependency
- add `@EnableCaching` annotation to your main class
- add `@CacheResult(cacheName = "books")` annotation to every method you want to cache
- add `spring.cache.type=jcache` to your `application.properties` file

For more explanation on the Spring Boot and JCache topic, please check the related Spring Boot blog post: https://spring.io/blog/2014/04/14/cache-abstraction-jcache-jsr-107-annotations-support[Cache Abstraction: JCache].

In our case, let's have a simple web service with two classes defined as follows:

.BookController.java
[source,java]
----
@RestController
@RequestMapping("/books")
public class BookController {

    private final BookService bookService;

    BookController(BookService bookService) {
        this.bookService = bookService;
    }

    @GetMapping("/{isbn}")
    public String getBookNameByIsbn(@PathVariable("isbn") String isbn) {
        return bookService.getBookNameByIsbn(isbn);
    }
}
----

.BookService.java
[source,java]
----
@Service
public class BookService {
    @CacheResult(cacheName = "books")
    public String getBookNameByIsbn(String isbn) {
        return findBookInSlowSource(isbn);
    }

    private String findBookInSlowSource(String isbn) {
        // some long processing
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
        return "Sample Book Name";
    }
}
----

The idea is that every call to the endpoint `/books/<isbn>` would go to the method `findBookNameByIsbn()`, which would attempt to return cached results.

If there's no cached value, the method would be executed and results cached.

== Using Hazelcast as JCache provider

We want to use Hazelcast as the JCache provider. The good news is that all you have to do it to add Hazelcast to your classpath:

.pom.xml
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast-all</artifactId>
</dependency>
----

Then, you need to add Hazelcast configuration choosing one of the below options:

- Add `hazelcast.yaml` configuration OR
- Add `hazelcast.xml` configuration OR
- Define `@Bean` with Hazelcast configuration in the source code

Let’s use the first option and add the following file into `src/main/resources`:

.hazelcast.yaml
[source,yaml]
----
hazelcast:
  cache:
    books:
      management-enabled: true
----

Finally, we need to specify the JCache provider in the `application.properties` file:

.application.properties
[source,properties]
----
spring.cache.type=jcache
spring.cache.jcache.provider=com.hazelcast.cache.impl.HazelcastServerCachingProvider
----

No more configuration needed, Hazelcast is already used as the cache manager for your project!

== Starting the Application

To start the application, run the following command.

----
mvn spring-boot:run
----

You should see in the logs that embedded Hazelcast has started.

----
Members {size:1, ver:1} [
        Member [172.30.63.9]:5701 - 75cd0b19-ee36-4e0a-9d9c-38c49f67f842 this
]
----

== Testing the Application

You can test the application by executing the following command.

----
curl localhost:8080/books/12345
Sample Book Name
----

The first time you execute this command, it should take some time to get the response. However, when you try it again, it should be instant. That means that the cache is used.

----
curl localhost:8080/books/12345
Sample Book Name
----

== What's more?

If you want to use Hazelcast in the client-server topology, then it's enough to use `HazelcastClientCachingProvider` instead of `HazelcastServerCachingProvider` in your `application.properties`.

If your want to learn more about Hazelcast as JCache provider, please check the official Hazelcast documentation: https://docs.hazelcast.org/docs/latest/manual/html-single/#hazelcast-jcache[Hazelcast JCache].
